'use strict';

const PB_STATUS = [['author_package','作者填写包'],['maker_review','制作方核验'],['asset_production','资源制作'],['data_implementation','数据 / DSL 实现'],['practice_battle','本地练习战验收'],['release_handoff','发布整合']];
const PB_ITEM_STATUS = [['missing','作者待提供'],['provided','已提供'],['reuse_official','复用官方'],['needs_review','待核验'],['not_applicable','不适用']];
const PB_SOURCE = [['new_recording','需要新录制'],['reuse_official','复用官方'],['to_generate','待生成'],['not_applicable','不适用']];
const PB_NATIVE = [['unknown','待核实'],['native_supported','原生支持'],['client_adaptation','需客户端适配'],['needs_verification','待制作方核验']];
const PB_REVIEW = [['unreviewed','未确认'],['pass','已通过'],['risk','有风险'],['not_applicable','不适用']];
const PB_REQUIRED_AUTHOR = new Set(['author.characterName','author.title','author.role','author.race','author.baseForm','author.evolvedForm']);
const PB_REQUIRED_PLANS = new Set(['plans.activeSkill.name','plans.activeSkill.authorDescription','plans.pf.name','plans.pf.authorDescription','plans.leader.name','plans.leader.authorDescription']);
const pbPath = path => path.split('.').reduce((value,key)=>value==null?undefined:value[key],S.p.productionBrief);
const pbValue = value => Array.isArray(value) ? value.join(', ') : (value ?? '');
function pbSet(path,value){mutate(()=>{const parts=path.split('.');let target=S.p.productionBrief;for(const key of parts.slice(0,-1))target=target[key];target[parts.at(-1)]=value;});}
function pbRequired(path,explicit=false){return explicit||PB_REQUIRED_AUTHOR.has(path)||PB_REQUIRED_PLANS.has(path);}
function pbBadge(required,text=required?'必填':'可选'){return `<span class="pb-badge ${required?'required':'optional'}">${text}</span>`;}
function pbLabel(path,label,required=false){return `<label for="pb-${path.replaceAll('.','-')}">${esc(label)} ${pbBadge(pbRequired(path,required))}</label>`;}
function pbInput(path,label,type='text',extra='',required=false){const must=pbRequired(path,required);return `<div class="field ${must?'field-required':''}">${pbLabel(path,label,must)}<input id="pb-${path.replaceAll('.','-')}" data-pb-path="${esc(path)}" type="${type}" value="${esc(pbValue(pbPath(path)))}" ${must?'required aria-required="true"':''} ${extra}></div>`;}
function pbText(path,label,extra='',required=false){const must=pbRequired(path,required);return `<div class="field ${must?'field-required':''}">${pbLabel(path,label,must)}<textarea id="pb-${path.replaceAll('.','-')}" data-pb-path="${esc(path)}" ${must?'required aria-required="true"':''} ${extra}>${esc(pbValue(pbPath(path)))}</textarea></div>`;}
function pbSelect(path,label,options,required=false){const must=pbRequired(path,required);return `<div class="field ${must?'field-required':''}">${pbLabel(path,label,must)}<select id="pb-${path.replaceAll('.','-')}" data-pb-path="${esc(path)}" ${must?'required aria-required="true"':''}>${options.map(([value,text])=>`<option value="${esc(value)}" ${String(value)===String(pbPath(path))?'selected':''}>${esc(text)}</option>`).join('')}</select></div>`;}
function pbPlan(path,title,plan){const core=PB_REQUIRED_PLANS.has(path+'.name'),started=Boolean(plan.name||plan.authorDescription),must=core||started;return `<section class="form-card production-plan ${core?'plan-required':''}"><div class="plan-heading"><h3>${esc(title)}</h3>${pbBadge(core,'必填：名称 + 说明')}${!core?pbBadge(started?'请补完整':'有此能力才填',started?'需补齐':'可选'):''}</div><p class="plan-help">${core?'稿主先写名称和一句自然语言说明；下面的补充项可以暂时留空。':'不用这个能力槽时保持空白；开始填写后，名称和说明需要一起完成。'}</p>${pbInput(path+'.name','名称','text','placeholder="例如：月影守护"',must)}${pbText(path+'.authorDescription','给制作方的一句话说明','rows="4" placeholder="按“何时 / 对谁 / 做什么 / 持续多久”来写，例如：受到攻击后，为全队提升攻击力 10 秒。"',must)}<details class="author-extra"><summary>补充表现意图（可选）</summary><div class="field-row">${pbInput(path+'.trigger','触发条件')}${pbInput(path+'.target','作用对象')}</div><div class="field-row">${pbInput(path+'.range','范围')}${pbInput(path+'.hits','段数 / 次数')}${pbInput(path+'.multiplier','倍率 / 数值')}</div><div class="field-row">${pbInput(path+'.duration','持续时间')}${pbInput(path+'.cooldown','冷却 / 刷新')}</div>${pbInput(path+'.statusIcon','状态 / 图标要求')}</details><details class="maker-details"><summary>制作方核验字段（稿主可留空）</summary><div class="field-row">${pbSelect(path+'.nativeSupport','原生机制支持',PB_NATIVE)}${pbInput(path+'.previewReference','对应预览 / 动作')}</div>${pbText(path+'.nativeConstraints','原生机制限制','rows="2"')}${pbText(path+'.verificationItems','待核实项','rows="2"')}${pbText(path+'.makerNotes','制作方备注','rows="2"')}</details></section>`;}
function pbResourceRow(item,index){const badge=pbBadge(item.required,item.required?'必填':'可选');return `<div class="production-row"><div class="production-row-title"><strong>${esc(item.label)} ${badge}</strong><small>${esc(item.frameHint||item.group)}</small></div><div>${pbSelect('resources.'+index+'.status','状态',PB_ITEM_STATUS)}</div><div>${pbInput('resources.'+index+'.assetIds','工程素材 ID（逗号分隔）')}</div><div class="production-row-extra"><span>参考 ${esc(item.expectedSize||'由制作方核定')} · 先填状态，再关联文件</span>${pbInput('resources.'+index+'.displaySize','实际显示尺寸')}${pbInput('resources.'+index+'.frameCount','帧数')}${pbInput('resources.'+index+'.atlasSize','图集尺寸')}${pbInput('resources.'+index+'.compression','压缩 / 编码')}${pbInput('resources.'+index+'.simultaneousBudget','同时在场预算')}${pbInput('resources.'+index+'.transparentBackground','透明背景检查')}${pbText('resources.'+index+'.notes','备注','rows="2"')}</div></div>`;}
function pbAudioRow(item,index,kind='voices'){const prefix=kind+'.'+index;const badge=pbBadge(item.required,item.required?'必填':'可选');return `<div class="production-row voice-requirement"><div class="production-row-title"><strong>${esc(item.label)} ${badge}</strong><small>${esc(item.usage)}${item.pairId?' · 进化前后成对':''}</small></div><div>${pbSelect(prefix+'.status','状态',PB_ITEM_STATUS)}${pbSelect(prefix+'.source','来源',PB_SOURCE)}</div><div>${pbInput(prefix+'.filename','文件名')}${pbInput(prefix+'.encoding','游戏编码 / 封装')}</div><div class="production-row-extra">${kind==='voices'?pbText(prefix+'.textJapanese','台词原文','rows="2" placeholder="没有台词时写“无台词”，不要留空"'):pbText(prefix+'.textJapanese','声音说明','rows="2" placeholder="例如：短促、明亮，命中时播放"')}<div class="field-row">${pbInput(prefix+'.dialect','方言参考')}${pbInput(prefix+'.toneReference','音色参考')}${pbInput(prefix+'.volume','音量')}${pbInput(prefix+'.duration','时长')}</div>${pbInput(prefix+'.assetId','工程音频素材 ID')}${pbText(prefix+'.notes','备注','rows="2"')}</div></div>`;}
function pbProgress(b){const authorKeys=[...PB_REQUIRED_AUTHOR];const authorDone=authorKeys.filter(key=>pbPath(key)).length;const corePlans=['activeSkill','pf','leader'];const planDone=corePlans.filter(key=>b.plans?.[key]?.name&&b.plans?.[key]?.authorDescription).length;const resources=(b.resources||[]).filter(x=>x.required);const voices=[...(b.voices||[]),...(b.sounds||[])].filter(x=>x.required);const ready=x=>x.status==='reuse_official'||x.status==='not_applicable'||(x.status==='provided'&&((x.assetIds||[]).length>0||Boolean(x.assetId)));return {author:[authorDone,authorKeys.length],plans:[planDone,corePlans.length],resources:[resources.filter(ready).length,resources.length],voices:[voices.filter(ready).length,voices.length]};}
function pbSummary(b){const p=pbProgress(b);return `<section class="production-required-summary"><div class="required-summary-head"><div><strong>先完成这四组必填内容</strong><p>红色“必填”是作者交接前需要提供的内容；灰色“可选”可留给制作方补充。</p></div><span class="pb-legend">${pbBadge(true)} ${pbBadge(false)} <span class="pb-badge review">待核验</span></span></div><div class="required-summary-grid">${[['角色基本信息',p.author],['主动技能 / PF / 队长技',p.plans],['必需图片与动作',p.resources],['必需语音与音效',p.voices]].map(([label,[done,total]])=>`<div class="required-summary-card"><strong>${esc(label)}</strong><span>${done} / ${total}</span><div class="required-progress"><i style="width:${total?Math.round(done/total*100):100}%"></i></div></div>`).join('')}</div></section>`;}
function renderProductionBrief(){
  const b=S.p.productionBrief||{};const a=b.author||{};const w=b.workflow||{};
  const stages=PB_STATUS.map(([key,label])=>`<span class="production-stage ${w.status===key?'current':''}">${label}</span>`).join('');
  $('#content').innerHTML=header('角色制作包','作者填写自然语言和资源需求，制作方在核验区补充技术结论。',`<a id="production-export" class="button primary" href="/api/production-handoff?id=${encodeURIComponent(S.p.id)}" download>导出制作交接 JSON ↗</a>`)+
  `<div class="production-intro"><strong>给稿主的填写页</strong><p>先完成红色“必填”项，再补充可选表现意图。这里不要求理解 ActionDSL、乘区、图集坐标或服务端代码；缺少的资源必须保持“待提供”，预览通过也不代表实战已验收。</p><div class="production-stages">${stages}</div></div>${pbSummary(b)}`+
  `<section class="form-card"><div class="section-title"><h3>流程状态与交接</h3><span class="hint">每阶段都可留下交接备注</span></div><div class="field-row">${pbSelect('workflow.status','当前阶段',PB_STATUS)}${pbText('workflow.statusNote','阶段说明','rows="2"')}</div><div class="handoff-grid">${(w.handoff||[]).map((row,i)=>`<label class="handoff-item"><input type="checkbox" data-pb-handoff="${i}" ${row.complete?'checked':''}><span><strong>${esc(row.label)}</strong><small>${esc(row.note||'')}</small></span></label>`).join('')}</div></section>`+
  `<section class="form-card"><div class="section-title"><h3>作者基本信息</h3><button id="production-copy-identity" class="quiet">从角色设定带入</button></div><div class="field-row">${pbInput('author.characterName','角色名')}${pbInput('author.title','称号')}${pbInput('author.element','属性')}${pbInput('author.role','职责 / 战斗定位')}${pbInput('author.race','种族')}</div><div class="field-row">${pbInput('author.baseForm','进化前形态')}${pbInput('author.evolvedForm','进化后形态')}</div><div class="field-row">${pbInput('author.characterIdReserved','角色 ID 预留')}${pbInput('author.resourceIdReserved','资源 ID 预留')}</div>${pbText('author.growth','基础成长 / 培养消耗','rows="3"')}${pbText('author.leaderPosition','队长定位','rows="2"')}${pbText('author.memberPosition','队员定位','rows="2"')}</section>`+
  `<details class="production-section" open><summary><strong>能力文本（稿主先填）</strong><span>主动技能、PF、队长技、能力 1-6</span></summary><p class="hint">前三项必须有“名称 + 一句话说明”；能力 1-6 是可选槽，开始填写某个槽后再把名称和说明补齐。建议用“何时 / 对谁 / 做什么 / 持续多久”描述，制作方核验字段在每项底部。</p><div class="form-layout">${pbPlan('plans.activeSkill','主动技能',b.plans?.activeSkill||{})}${pbPlan('plans.pf','PF',b.plans?.pf||{})}${pbPlan('plans.leader','队长技',b.plans?.leader||{})}</div><div class="gameplay-abilities production-ability-grid">${(b.plans?.abilities||[]).map((plan,i)=>pbPlan('plans.abilities.'+i,'能力 '+plan.slot,plan)).join('')}</div></details>`+
  `<details class="production-section"><summary><strong>资源清单</strong><span>立绘、UI、像素动作、技能/PF 帧集、图标与图集</span></summary><p class="hint">每一行都标明必填或可选。先选“状态”，再关联工程素材 ID；图集尺寸、压缩、帧数、透明背景和同时在场预算都可记录。</p><div class="production-list">${(b.resources||[]).map(pbResourceRow).join('')}</div></details>`+
  `<details class="production-section"><summary><strong>语音与音效清单</strong><span>角色说话、技能喊声、施放与命中声音</span></summary><p class="hint">角色语音与技能音效分开记录。语音行用于台词/喊声；音效行用于施放、命中、蓄力等声音，之后可绑定到技能特效的声音事件和时间轴。</p><h4 class="production-subheading">角色语音</h4><div class="production-list">${(b.voices||[]).map((item,i)=>pbAudioRow(item,i,'voices')).join('')}</div><h4 class="production-subheading">技能 / 战斗音效</h4><div class="production-list">${(b.sounds||[]).map((item,i)=>pbAudioRow(item,i,'sounds')).join('')}</div></details>`+
  `<details class="production-section"><summary><strong>稳定经验检查</strong><span>稻穗首轮制作复盘沉淀的防错项</span></summary><div class="production-review-list">${(b.review||[]).map((item,i)=>`<div class="review-item"><div><strong>${esc(item.label)}</strong><p>${esc(item.note)}</p></div>${pbSelect('review.'+i+'.state','状态',PB_REVIEW)}${pbText('review.'+i+'.note','核验记录','rows="2"')}</div>`).join('')}</div></details>`+
  `<section class="form-card"><h3>验收与版本链</h3><div class="notice">预览播放不等于实战。实战只用练习战验证，并记录自动战斗、目标阵容和退出后的活动记录恢复。</div><div class="field-row">${pbSelect('acceptance.practiceBattleStatus','练习战状态',[['not_run','未进行'],['passed','已通过'],['failed','失败'],['blocked','被阻断']])}${pbSelect('acceptance.automaticBattle','自动战斗已覆盖',[['false','未覆盖'],['true','已覆盖']])}${pbInput('acceptance.targetParty','目标阵容')}</div><div class="field-row">${pbInput('acceptance.localCdnVersion','本地 CDN 版本')}${pbInput('acceptance.cloudReleaseVersion','正式云服版本')}</div>${pbText('acceptance.activityRecovery','活动记录 / H400 / C3212 区分','rows="3"')}${pbText('acceptance.notes','验收备注','rows="3"')}</section>`+
  `<section class="form-card"><h3>制作方交接文件</h3><p>导出的 JSON 只包含填写包、技术核验状态、资源/语音清单和检查结果，不包含二进制素材或账号信息。</p><div class="production-actions"><a class="button primary" href="/api/production-handoff?id=${encodeURIComponent(S.p.id)}" download>下载制作交接 JSON</a><button id="production-run-check">刷新缺项检查</button></div><div id="production-check-result" class="hint"></div></section>`;
  bindProductionBrief();
}
function bindProductionBrief(){
  $$('[data-pb-path]').forEach(input=>input.onchange=()=>{const path=input.dataset.pbPath;let value=input.value;if(input.tagName==='SELECT'&&path==='acceptance.automaticBattle')value=value==='true';if(path.match(/^resources\.\d+\.assetIds$/))value=value.split(',').map(item=>item.trim()).filter(Boolean);pbSet(path,value);});
  $$('[data-pb-handoff]').forEach(input=>input.onchange=()=>mutate(()=>S.p.productionBrief.workflow.handoff[Number(input.dataset.pbHandoff)].complete=input.checked));
  $('#production-copy-identity').onclick=()=>mutate(()=>{const i=S.p.identity||{},a=S.p.productionBrief.author;a.characterName=S.p.name||a.characterName;a.title=i.title||a.title;a.element=i.element||a.element;a.role=i.role||a.role;a.race=i.race||a.race;});
  $('#production-run-check').onclick=()=>busy('检查制作填写包',async()=>{await saveNow();const result=await api('/api/check?id='+encodeURIComponent(S.p.id));const node=$('#production-check-result');node.textContent=`当前有 ${result.issues.filter(i=>i.page==='production').length} 项制作填写包提示；详细结果请查看“检查与交付”。`;});
}
